// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`ErrorBoundary component:  should render children when no error 1`] = `<div />`;

exports[`ErrorBoundary component:  should render when error is caught 1`] = `
.c0 {
  max-width: 480px;
  margin: 0 auto;
  -webkit-align-self: center;
  -ms-flex-item-align: center;
  align-self: center;
  padding: 40px;
  background-color: white;
  box-shadow: 0 3px 6px rgba(0,0,0,0.16),0 3px 6px rgba(0,0,0,0.23);
}

.c0 h1 {
  font-size: 24px;
  margin: 0 0 20px 0;
  text-align: center;
}

.c0 p {
  margin-bottom: 20px;
  text-align: center;
}

.c0 footer {
  text-align: center;
}

.c1 {
  color: #f33;
}

<ErrorBoundary>
  <ErrorBoundary___default>
    <div
      className="c0"
    >
      <h1>
        Oh no! You have hit an error that should never have made it into the app!
      </h1>
      <Base__ErrorP>
        <p
          className="c1"
        >
          message
        </p>
      </Base__ErrorP>
      <footer>
        Let me know about this problem via email at 
        <a
          href="mailto:bmpieretti@gmail.com?subject=Incident%20Report&amp;body=message--info"
        >
          bmpieretti@gmail.com
        </a>
        .
      </footer>
    </div>
  </ErrorBoundary___default>
</ErrorBoundary>
`;
